### ISSUE TITLE
Is Pyre currently compatible with Zyre current version ?

### ISSUE THREAD

**Issue by dmaugis** [zeromq/pyre#125]
The README.md on https://gitlab.tkn.tu-berlin.de/wishful/pyre states:
"This is a Python port of Zyre **1.0**, implementing the same ZRE protocol.
But I see some commits to make Pyre compatible with Zyre and ZRE v2...
So, which one is it ???
Is Pyre currently compatible with Zyre current version ???

**Comment by sphaero** [comment]
No, there is an older version of Zyre which is compatible but I can't point to the exact version. For mixing python and C (zyre) I recommend to use the Zyre python bindings instead of Pyre. There's currently no effort in making them compatible but pull request are very welcomed.

Pyre was written back in the ZRE 1.0 days and picked up some of the ZRE 2.0, mostly beaconing if I recall correctly.
