### ISSUE TITLE
Calling Pyre.stop() while Pyre.recv() is blocking?

### ISSUE THREAD

**Issue by utsavdrolia** [zeromq/pyre#54]
Maybe my design choice was poor, but, I have a thread that calls the recv() method and does stuff. When the program is done, I want to stop the nodes. But if I call Pyre.stop() from the main thread while the other thread is blocking on the recv() call, python refuses to shutdown the program.

**Comment by sphaero** [comment]
Welcome to asynchronous programming :) Indeed you cannot stop while a call is blocking and you certainly should not use threads for that. You should use a poller instead of calling recv. The recv method just calls self.inbox.recv_multipart() I would register self.inbox to a poller. A poller you can give a timeout. But do rethink your design. Always try to come up with a non threaded design. Once you go into threads prepare to be bitten.

For an example look at the pyre_node class's run method.

**Comment by utsavdrolia** [comment]
I did not know about the Poller earlier - this is really handy!
Though, should there be 2 methods - one blocking and another non-blocking that returns None when nothing is available?

**Comment by sphaero** [comment]
What do you think of this PR I just made. It makes the API similar to PyZMQ so you can call node.recv_multipart(zmq.NOBLOCK) for example.

**Comment by utsavdrolia** [comment]
Yes, this looks good :+1: 
About the multipart:
Will it return multiple pyre frames? Or will the received list of frames need to be 'combined' to form 1 pyre frame?

**Comment by sphaero** [comment]
recv_multipart returns the frame which is a list of messages in PyZMQ.
Actually this PR breaks the user API as recv now returns a single message and you are responsible for fetching all messages. This needs some reflection I guess.

**Comment by blink1073** [comment]
I think in this case `recv` should receive a full message from the node.  The user can always use `inbox.recv()` if they really wanted to get low-level and receive one part at a time.

**Comment by sphaero** [comment]
It's do we follow the PyZMQ api or do we follow the Zyre API. I guess the latter. But then we should document how to access at PyZMQ level.

**Comment by blink1073** [comment]
Agreed on both accounts.

**Comment by sphaero** [comment]
Ow man definetly not merging this PR, it already shot me in the foot.
Going for education thus we need more documentation for showing how you can access the ZMQ sockets.
